package com.allen.loltool.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.allen.loltool.greendao.HeroListItem;
import com.allen.loltool.greendao.FreeHeroListItem;

import com.allen.loltool.greendao.HeroListItemDao;
import com.allen.loltool.greendao.FreeHeroListItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig heroListItemDaoConfig;
    private final DaoConfig freeHeroListItemDaoConfig;

    private final HeroListItemDao heroListItemDao;
    private final FreeHeroListItemDao freeHeroListItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        heroListItemDaoConfig = daoConfigMap.get(HeroListItemDao.class).clone();
        heroListItemDaoConfig.initIdentityScope(type);

        freeHeroListItemDaoConfig = daoConfigMap.get(FreeHeroListItemDao.class).clone();
        freeHeroListItemDaoConfig.initIdentityScope(type);

        heroListItemDao = new HeroListItemDao(heroListItemDaoConfig, this);
        freeHeroListItemDao = new FreeHeroListItemDao(freeHeroListItemDaoConfig, this);

        registerDao(HeroListItem.class, heroListItemDao);
        registerDao(FreeHeroListItem.class, freeHeroListItemDao);
    }
    
    public void clear() {
        heroListItemDaoConfig.getIdentityScope().clear();
        freeHeroListItemDaoConfig.getIdentityScope().clear();
    }

    public HeroListItemDao getHeroListItemDao() {
        return heroListItemDao;
    }

    public FreeHeroListItemDao getFreeHeroListItemDao() {
        return freeHeroListItemDao;
    }

}
