package com.allen.loltool.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FREE_HERO_LIST_ITEM".
 */
public class FreeHeroListItem {

    private Long id;
    private String end_time;
    private String start_time;
    private String en_name;
    private String name;
    private String img;
    private String money;
    private String coin;
    private String heroid;
    private String newmoney;
    private String newhero;

    public FreeHeroListItem() {
    }

    public FreeHeroListItem(Long id) {
        this.id = id;
    }

    public FreeHeroListItem(Long id, String end_time, String start_time, String en_name, String name, String img, String money, String coin, String heroid, String newmoney, String newhero) {
        this.id = id;
        this.end_time = end_time;
        this.start_time = start_time;
        this.en_name = en_name;
        this.name = name;
        this.img = img;
        this.money = money;
        this.coin = coin;
        this.heroid = heroid;
        this.newmoney = newmoney;
        this.newhero = newhero;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEnd_time() {
        return end_time;
    }

    public void setEnd_time(String end_time) {
        this.end_time = end_time;
    }

    public String getStart_time() {
        return start_time;
    }

    public void setStart_time(String start_time) {
        this.start_time = start_time;
    }

    public String getEn_name() {
        return en_name;
    }

    public void setEn_name(String en_name) {
        this.en_name = en_name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getMoney() {
        return money;
    }

    public void setMoney(String money) {
        this.money = money;
    }

    public String getCoin() {
        return coin;
    }

    public void setCoin(String coin) {
        this.coin = coin;
    }

    public String getHeroid() {
        return heroid;
    }

    public void setHeroid(String heroid) {
        this.heroid = heroid;
    }

    public String getNewmoney() {
        return newmoney;
    }

    public void setNewmoney(String newmoney) {
        this.newmoney = newmoney;
    }

    public String getNewhero() {
        return newhero;
    }

    public void setNewhero(String newhero) {
        this.newhero = newhero;
    }

}
