package com.allen.loltool.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.allen.loltool.greendao.FreeHeroListItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FREE_HERO_LIST_ITEM".
*/
public class FreeHeroListItemDao extends AbstractDao<FreeHeroListItem, Long> {

    public static final String TABLENAME = "FREE_HERO_LIST_ITEM";

    /**
     * Properties of entity FreeHeroListItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property End_time = new Property(1, String.class, "end_time", false, "END_TIME");
        public final static Property Start_time = new Property(2, String.class, "start_time", false, "START_TIME");
        public final static Property En_name = new Property(3, String.class, "en_name", false, "EN_NAME");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Img = new Property(5, String.class, "img", false, "IMG");
        public final static Property Money = new Property(6, String.class, "money", false, "MONEY");
        public final static Property Coin = new Property(7, String.class, "coin", false, "COIN");
        public final static Property Heroid = new Property(8, String.class, "heroid", false, "HEROID");
        public final static Property Newmoney = new Property(9, String.class, "newmoney", false, "NEWMONEY");
        public final static Property Newhero = new Property(10, String.class, "newhero", false, "NEWHERO");
    };


    public FreeHeroListItemDao(DaoConfig config) {
        super(config);
    }
    
    public FreeHeroListItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FREE_HERO_LIST_ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"END_TIME\" TEXT," + // 1: end_time
                "\"START_TIME\" TEXT," + // 2: start_time
                "\"EN_NAME\" TEXT," + // 3: en_name
                "\"NAME\" TEXT," + // 4: name
                "\"IMG\" TEXT," + // 5: img
                "\"MONEY\" TEXT," + // 6: money
                "\"COIN\" TEXT," + // 7: coin
                "\"HEROID\" TEXT," + // 8: heroid
                "\"NEWMONEY\" TEXT," + // 9: newmoney
                "\"NEWHERO\" TEXT);"); // 10: newhero
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FREE_HERO_LIST_ITEM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FreeHeroListItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String end_time = entity.getEnd_time();
        if (end_time != null) {
            stmt.bindString(2, end_time);
        }
 
        String start_time = entity.getStart_time();
        if (start_time != null) {
            stmt.bindString(3, start_time);
        }
 
        String en_name = entity.getEn_name();
        if (en_name != null) {
            stmt.bindString(4, en_name);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(6, img);
        }
 
        String money = entity.getMoney();
        if (money != null) {
            stmt.bindString(7, money);
        }
 
        String coin = entity.getCoin();
        if (coin != null) {
            stmt.bindString(8, coin);
        }
 
        String heroid = entity.getHeroid();
        if (heroid != null) {
            stmt.bindString(9, heroid);
        }
 
        String newmoney = entity.getNewmoney();
        if (newmoney != null) {
            stmt.bindString(10, newmoney);
        }
 
        String newhero = entity.getNewhero();
        if (newhero != null) {
            stmt.bindString(11, newhero);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FreeHeroListItem readEntity(Cursor cursor, int offset) {
        FreeHeroListItem entity = new FreeHeroListItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // end_time
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // start_time
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // en_name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // img
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // money
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // coin
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // heroid
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // newmoney
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // newhero
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FreeHeroListItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEnd_time(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStart_time(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEn_name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setImg(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setMoney(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCoin(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setHeroid(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setNewmoney(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setNewhero(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FreeHeroListItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FreeHeroListItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
