package com.allen.loltool.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HERO_LIST_ITEM".
 */
public class HeroListItem {

    private Long id;
    private Integer total_pages;
    private Integer limit;
    private Integer total;
    private Integer page;
    private String version;
    private String en_name;
    private String name;
    private String img;
    private String money;
    private String coin;
    private String heroid;
    private String newmoney;
    private String newhero;

    public HeroListItem() {
    }

    public HeroListItem(Long id) {
        this.id = id;
    }

    public HeroListItem(Long id, Integer total_pages, Integer limit, Integer total, Integer page, String version, String en_name, String name, String img, String money, String coin, String heroid, String newmoney, String newhero) {
        this.id = id;
        this.total_pages = total_pages;
        this.limit = limit;
        this.total = total;
        this.page = page;
        this.version = version;
        this.en_name = en_name;
        this.name = name;
        this.img = img;
        this.money = money;
        this.coin = coin;
        this.heroid = heroid;
        this.newmoney = newmoney;
        this.newhero = newhero;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTotal_pages() {
        return total_pages;
    }

    public void setTotal_pages(Integer total_pages) {
        this.total_pages = total_pages;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getEn_name() {
        return en_name;
    }

    public void setEn_name(String en_name) {
        this.en_name = en_name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getMoney() {
        return money;
    }

    public void setMoney(String money) {
        this.money = money;
    }

    public String getCoin() {
        return coin;
    }

    public void setCoin(String coin) {
        this.coin = coin;
    }

    public String getHeroid() {
        return heroid;
    }

    public void setHeroid(String heroid) {
        this.heroid = heroid;
    }

    public String getNewmoney() {
        return newmoney;
    }

    public void setNewmoney(String newmoney) {
        this.newmoney = newmoney;
    }

    public String getNewhero() {
        return newhero;
    }

    public void setNewhero(String newhero) {
        this.newhero = newhero;
    }

}
